name: testproject
on: push
jobs:
    secondjob:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - run: npm ci
            - run: npm test