name: Deployment
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - run: npm ci
            - run: npm test
    deployment:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - run: npm ci
            - run: npm test
            - name: Build Project
              run: echo "deploying"
